# Generated by Django 5.1 on 2024-08-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_publicacion', models.DateField(auto_now=True, verbose_name='Fecha Publicación')),
                ('categoria', models.SmallIntegerField(choices=[(0, 'Sin definir'), (2, 'Romance'), (3, 'Acción'), (4, 'Terror'), (4, 'Comedia')], default=0, verbose_name='Categoría')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.autor', verbose_name='Autor')),
            ],
        ),
    ]
