# Generated by Django 5.1 on 2024-08-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha Actualizción'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(verbose_name='Fecha Publicación'),
        ),
    ]
